## Copyright  2018 Aram Meem Company Limited. All Rights Reserved.

## Java Maven CircleCI 2.0 configuration file
version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/repo # directory where steps will run

    docker: # run the steps with Docker
    - image: circleci/openjdk:8-jdk-browsers # ...with this image as the primary container; this is where all `steps` will run

    steps: # a collection of executable commands

    - checkout # check out source code to working directory

    - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
        key: dependency-cache-{{ checksum "pom.xml" }}

    - run:
        name: Maven Dependency Go Offline
        command: mvn dependency:go-offline # gets the project dependencies

    - save_cache: # saves the project dependencies
        paths:
        - ~/.m2
        key: dependency-cache-{{ checksum "pom.xml" }}

    - run:
        name: Login Page Test
        command: mvn -Dtest=LoginTest test
        when: always

workflows:
  version: 2
  commit-workflow:
    jobs:
    - build
        branches:
          only: master